### Importing Required Libraries

In [1]:
import pandas as pd

C:\Users\gopib\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
df = pd.read_csv(r"C:\Users\gopib\Downloads\hyderabad_eta_data.csv")
df

,start_lat,start_lng,end_lat,end_lng,distance_km,traffic_density,weather_condition,day_of_week,hour_of_day,ETA
0,17.312362,78.355540,17.278512,78.501811,17.587880,3,rainy,3,17,26.113020
1,17.485214,78.462570,17.274094,78.539004,24.357538,8,clear,5,14,58.715248
2,17.419598,78.561884,17.471876,78.375140,23.044667,7,rainy,6,8,59.316409
3,17.379598,78.519667,17.274864,78.487462,5.463097,3,clear,2,17,35.630253
4,17.246806,78.541968,17.281585,78.471524,5.328235,6,clear,1,2,56.713490
...,...,...,...,...,...,...,...,...,...,...
995,17.227475,78.497087,17.459589,78.432632,27.024522,9,clear,2,4,18.585042
996,17.475194,78.586984,17.247182,78.400320,4.462049,1,rainy,5,14,42.688225
997,17.241046,78.320687,17.292936,78.418372,10.507442,1,clear,5,12,11.273635
998,17.485071,78.317116,17.287014,78.458982,24.656616,4,rainy,5,12,13.180450
999,17.333802,78.384656,17.461424,78.348410,18.322059,4,rainy,3,12,21.053944

###  EDA

In [3]:
df.isna().sum()

start_lat            0
start_lng            0
end_lat              0
end_lng              0
distance_km          0
traffic_density      0
weather_condition    0
day_of_week          0
hour_of_day          0
ETA                  0
dtype: int64

In [4]:
df.duplicated().sum()

0

In [5]:
df.corr(numeric_only=True)

,start_lat,start_lng,end_lat,end_lng,distance_km,traffic_density,day_of_week,hour_of_day,ETA
start_lat,1.000000,0.029310,0.014518,-0.029424,0.034785,-0.024754,0.055406,-0.014557,-0.030701
start_lng,0.029310,1.000000,0.027262,-0.005791,0.032911,0.000297,-0.048353,0.014242,-0.007978
end_lat,0.014518,0.027262,1.000000,-0.013560,-0.008858,-0.014043,-0.057856,-0.006245,0.061752
end_lng,-0.029424,-0.005791,-0.013560,1.000000,-0.044812,0.034494,0.017789,-0.012494,0.009425
distance_km,0.034785,0.032911,-0.008858,-0.044812,1.000000,-0.031475,0.066093,0.022646,-0.008686
traffic_density,-0.024754,0.000297,-0.014043,0.034494,-0.031475,1.000000,-0.010457,0.018572,-0.009196
day_of_week,0.055406,-0.048353,-0.057856,0.017789,0.066093,-0.010457,1.000000,0.020010,0.072280
hour_of_day,-0.014557,0.014242,-0.006245,-0.012494,0.022646,0.018572,0.020010,1.000000,0.009233
ETA,-0.030701,-0.007978,0.061752,0.009425,-0.008686,-0.009196,0.072280,0.009233,1.000000

## Data Cleaning

### Feature Engineering

In [6]:
df = df.drop(columns=["start_lat","start_lng","end_lat","end_lng"])          # we don't need lat and long as we have distances

In [7]:
df

,distance_km,traffic_density,weather_condition,day_of_week,hour_of_day,ETA
0,17.587880,3,rainy,3,17,26.113020
1,24.357538,8,clear,5,14,58.715248
2,23.044667,7,rainy,6,8,59.316409
3,5.463097,3,clear,2,17,35.630253
4,5.328235,6,clear,1,2,56.713490
...,...,...,...,...,...,...
995,27.024522,9,clear,2,4,18.585042
996,4.462049,1,rainy,5,14,42.688225
997,10.507442,1,clear,5,12,11.273635
998,24.656616,4,rainy,5,12,13.180450
999,18.322059,4,rainy,3,12,21.053944

In [8]:
df["weather_condition"]=df["weather_condition"].map({'rainy':1,'foggy':2,'clear':3})

## Model Building

### splitting the data

In [9]:
df

,distance_km,traffic_density,weather_condition,day_of_week,hour_of_day,ETA
0,17.587880,3,1,3,17,26.113020
1,24.357538,8,3,5,14,58.715248
2,23.044667,7,1,6,8,59.316409
3,5.463097,3,3,2,17,35.630253
4,5.328235,6,3,1,2,56.713490
...,...,...,...,...,...,...
995,27.024522,9,3,2,4,18.585042
996,4.462049,1,1,5,14,42.688225
997,10.507442,1,3,5,12,11.273635
998,24.656616,4,1,5,12,13.180450
999,18.322059,4,1,3,12,21.053944

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X = df.drop('ETA',axis = 1)
y = df['ETA']

In [12]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=23)

In [13]:
X_train

     distance_km  traffic_density  weather_condition  day_of_week  hour_of_day
228    14.519266                5                  1            0           19
45     13.397107                4                  3            6            7
373    12.536010               10                  3            1           13
813    15.841633               10                  1            4            5
448    10.691589                1                  2            2           16
..           ...              ...                ...          ...          ...
950    12.456547                2                  3            5           21
969    13.386046                4                  1            0           20
40     26.116945                1                  3            0            0
742     2.032117                4                  1            1            7
595    19.711339                3                  2            0           21

[800 rows x 5 columns]

In [14]:
X_test

     distance_km  traffic_density  weather_condition  day_of_week  hour_of_day
519     1.654371                2                  2            2            3
837    12.991979                5                  3            4            0
208     3.494933               10                  1            0            9
525    13.460528                3                  1            5           16
978     1.027359                3                  2            0           20
..           ...              ...                ...          ...          ...
647     8.317127                3                  2            0            2
481    14.680455                4                  2            5           21
134    18.210380                8                  2            3           23
366     3.323066                7                  3            0           14
879    24.895932                3                  2            4           15

[200 rows x 5 columns]

In [15]:
y_train

228    30.398130
45     44.762920
373    47.206334
813    11.779107
448    49.694668
         ...
950    39.117873
969    28.932119
40     31.858602
742    48.063773
595    40.240088
Name: ETA, Length: 800, dtype: float64

In [16]:
y_test

519    16.759153
837    58.410396
208    30.799480
525    39.120048
978    42.558848
         ...
647    12.961165
481    54.782646
134    59.535628
366    50.594482
879    57.981308
Name: ETA, Length: 200, dtype: float64

## Linear Regression

In [17]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score,mean_absolute_error,r2_score,mean_squared_error
import numpy as np

In [18]:
lr = LinearRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)
np.sqrt(mean_squared_error(y_test,y_pred))

15.058318809639673

## KNN Regression

In [19]:
from sklearn.neighbors import KNeighborsRegressor
knn=KNeighborsRegressor()
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)
mean_squared_error(y_test,y_pred)

243.85697671555275

## Decision Treee

In [20]:
from sklearn.tree import DecisionTreeRegressor
dt=DecisionTreeRegressor()
dt.fit(X_train,y_train)
y_pred = dt.predict(X_test)
mean_squared_error(y_test,y_pred)

426.7749583007558

## SVR

In [21]:
from sklearn.svm import SVR
sv=SVR()
sv.fit(X_train,y_train)
y_pred = sv.predict(X_test)
mean_squared_error(y_test,y_pred)

231.75158346232888

In [22]:
lr.coef_

array([-0.05354114, -0.12767925,  0.14473181,  0.51686871,  0.05911873])

In [23]:
lr.intercept_

34.36881523147063

## Deployement

In [24]:
# for getting latitudes and longitudes of the area for user input

import requests

def get_lat_long(area_name, city_name, country_name):
    url = f"https://nominatim.openstreetmap.org/search?q={area_name},{city_name},{country_name}&format=json"


    request_header = {'Content-Type': 'text/html; charset=UTF-8','User-Agent': 'Chrome/101.0.0.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0','Accept-Encoding': 'gzip, deflate, br'}

    response = requests.get(url, headers=request_header)

    if response.status_code == 200:
        data = response.json()
        if data:
            lat = float(data[0]['lat'])
            lng = float(data[0]['lon'])
            return lat, lng
        else:
            return None, None
    else:
        print(f"Error: {response.status_code}")
        return None, None


area_name = input("Enter the area name: ")
city_name = "Hyderabad"  
country_name = "India"

lat, lng = get_lat_long(area_name, city_name, country_name)

if lat and lng:
    print(f"Latitude: {lat}, Longitude: {lng}")
else:
    print("No results found or unable to fetch data.")

Enter the area name: kukatpally
Latitude: 17.4930841, Longitude: 78.4054408

In [25]:
# for calculating distance between to areas by it's latitudes and longitudes

import math

def haversine(lat1, lon1, lat2, lon2):

    lat1, lon1, lat2, lon2 = map(math.radians, [lat1, lon1, lat2, lon2])

    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = math.sin(dlat / 2)**2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon / 2)**2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    r = 6371  
    return r * c


lat1, lon1 = 17.312362, 78.355540  
lat2, lon2 = 17.278512, 78.501811  

distance = haversine(lat1, lon1, lat2, lon2)
print(f"Distance: {distance} km")

Distance: 15.978821938622854 km

In [26]:
city_name = "Hyderabad"  
country_name = "India"


starting = input("Enter starting area : ")
destination = input("Enter destination area : ")
density=int(input("Enter the density: "))
weather = int(input("Enter the weather "))
day=int(input("Enter the day: "))
hour=int(input("Enter the hour: "))
start_lat,start_long = get_lat_long(starting,city_name,country_name)
end_lat,end_long = get_lat_long(destination,city_name,country_name)
dist = haversine(start_lat,start_long,end_lat,end_long)

time=lr.predict([[dist,density,weather,day,hour]])
print("The Estimated time is",time)

Enter starting area : kukatpally
Enter destination area : ameerpet
Enter the density: 7
Enter the weather 1
Enter the day: 5
Enter the hour: 19
The Estimated time is [36.91677046]

C:\Users\gopib\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

## Pickle the model

In [27]:
import pickle
pickle.dump(lr,open("estimator.pkl",'wb'))